### ISSUE TITLE
Text in bubble is not displaying properly on older APIs

### ISSUE THREAD

**Issue by Mathbl** [himanshu-soni/ChatMessageView#5]
Not sure why this happens. It seems like the text is not wrapping correctly on older apis. Here's a screenshot of the word "test".
![screen shot 2015-10-20 at 10 23 48](https://cloud.githubusercontent.com/assets/906656/10610249/01f6cca4-7715-11e5-9d35-11288d178af6.png)

I'm testing on a Galaxy Nexus running 4.2 and an emulator running 4.1. It's not happening on Lollipop. Thanks.

**Comment by himanshu-soni** [comment]
fixed in #6

**Comment by Mathbl** [comment]
PR #6 doesn't address this bug. I have no solution for this one. We should reopen.

**Comment by Mathbl** [comment]
Still not working as of 1.0.3. 

Tested on 4.2 and 4.1, it still displays like the screenshot above.

**Comment by himanshu-soni** [comment]
Hi @Mathbl 
I am not seeing such view in my 4.1 emulator. can you show me code with the example

**Comment by Mathbl** [comment]
Hi @himanshu-soni 
First, I just created a standard emulator with android studio:
![screen shot 2016-03-14 at 12 00 20 pm](https://cloud.githubusercontent.com/assets/906656/13750575/7e17b1b0-e9dc-11e5-83e3-66ed9788d1a8.png)

Here's my layout code:

```
<me.himanshusoni.chatmessageview.ChatMessageView
    android:id="@+id/message_view"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    classcraft:cmv_arrowGravity="center"
    classcraft:cmv_arrowMargin="3dp"
    classcraft:cmv_arrowPosition="right"
    classcraft:cmv_backgroundColor="@color/gray_light"
    classcraft:cmv_backgroundColorPressed="@color/gray_light"
    classcraft:cmv_contentPadding="@dimen/content_spacing_small"
    classcraft:cmv_cornerRadius="6dp"
    classcraft:cmv_showArrow="true"
    >

    <TextView
        android:id="@+id/message_text"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_margin="@dimen/content_spacing_xsmall"
        android:textColor="@color/gray_dark"
        android:textSize="@dimen/font_size_normal"
        />

</me.himanshusoni.chatmessageview.ChatMessageView>
```

Note that this is part of a listview item layout. In my listview adapter, I simply do `holder.messageText.setText(message.getText());`

If you need more info, I'll try to help.

**Comment by himanshu-soni** [comment]
Hi @Mathbl I have checked in 4.1.1 emulator and devices as well. it is working. please confirm. I am closing this issue.
